BaseURL: http://www.swirl-project.org
languageCode: en-nz
title: Bringing Peer-to-Peer Streaming to the World
author:
    name: the Swirl Project
builddrafts: false
theme: hyde-x
metadataformat: yaml
canonifyurls: false
relativeURLs: true
contentdir: ../doc
publishdir: ../public
permalinks:
  post: blog/:year/:month/:day/:filename
  archive: archive/:year/:month/:day/:filename
  talk: talks/:year/:filename
params:
  defaultDescription: Bringing Peer-to-Peer Streaming to the World
  defaultKeywords: p2p,ppspp,streaming
  highlight: monokai_sublime
  tagline: Bringing Peer-to-Peer Streaming to the World
  copyright: "Copyright (c) 2014 - 2038 Skunkwerks GmbH; all rights reserved."
  blog: http://www.swirl-project.org/blog
  github: https://github.com/skunkwerks/swirl
  twitter: http://twitter.com/swirl_project
  datatracker: https://datatracker.ietf.org/doc/draft-ietf-ppsp-peer-protocol
  ppspp: http://tools.ietf.org/html/draft-ietf-ppsp-peer-protocol
  tracker: http://tools.ietf.org/html/draft-ietf-ppsp-base-tracker-protocol
taxonomies:
    tag: tags
...
